### ISSUE TITLE
sub-layouts not rendering with custom delims

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/layouts#1]
https://github.com/assemble/assemble/issues/626

**Comment by doowb** [comment]
Wasn't this because template was passing the wrong delimiters or there was a version mismatch between the libraries and the delimiters were on the wrong property? I think this was fixed.

**Comment by jonschlinkert** [comment]
maybe, but the other issue wasn't closed. let's close and reopen if necessary

**Comment by doowb** [comment]
I just verified with the example repo that it works as expected now.

**Comment by jonschlinkert** [comment]
:+1:
